version: '3'
services:
  web:
    tty: true
    stdin_open: true
    container_name: rideshare_web
    image: hodai1508/rideshare-ruby:dev
    build:
      context: .
      dockerfile: Dockerfile
    command: sh docker/start.sh
    entrypoint: []
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

volumes:
  rideshare_web:
